### ISSUE TITLE
SHAKEN/STIR properties missing from VoiceRequest?

### ISSUE THREAD

**Issue by ericsampson** [twilio-labs/twilio-aspnet#65]
I believe that the following properties are missing from VoiceRequest:
```
public string StirPassportToken { get; set; }
public string StirVerstat { get; set; }
```

**Comment by Swimburger** [comment]
@ericsampson thank you for reporting this!

@dprothero since the amount of parameters passed via a webhook request keeps increasing, should we keep adding them as new properties until the class becomes very large, or should only add the most common, and suggest parsing the querystring for GET and form body for POST?

**Comment by ericsampson** [comment]
fwiw, These particular ones are important enough to add since things won't work if they're not used

**Comment by Swimburger** [comment]
I suggest extending the class yourself if you want to use model binding or directly pulling it from the form collection which is more performant.

I'm going to do my best to keep the classes in sync with the [documented request parameters](https://www.twilio.com/docs/voice/twiml#request-parameters), and leave the other parameters that come from more specific scenarios up to the developer to handle themselves.
